INSERT INTO TODO (DONE,ID,PRIORITY,TARGET_DATE,DESCRIPTION,USERNAME)
VALUES (false,1,0 ,CURRENT_DATE(),'DO HSR STORY QUEST','guactimusprime');
INSERT INTO TODO (DONE,ID,PRIORITY,TARGET_DATE,DESCRIPTION,USERNAME)
VALUES (false,2,1 ,CURRENT_DATE(),'PURGE THE PLANET','guactimusprime');
INSERT INTO TODO (DONE,ID,PRIORITY,TARGET_DATE,DESCRIPTION,USERNAME)
VALUES (false,3,2 ,CURRENT_DATE(),'GET BACK TO WORK','guactimusprime');
INSERT INTO TODO (DONE,ID,PRIORITY,TARGET_DATE,DESCRIPTION,USERNAME)
VALUES (false,4,1 ,CURRENT_DATE(),'GET A BETTER JOB','guactimusprime');
INSERT INTO TODO (DONE,ID,PRIORITY,TARGET_DATE,DESCRIPTION,USERNAME)
VALUES (false,5,0 ,CURRENT_DATE(),'GET BOOKMARKS FOR JENUA','guactimusprime');
INSERT INTO TODO (DONE,ID,PRIORITY,TARGET_DATE,DESCRIPTION,USERNAME)
VALUES (false,6,1 ,CURRENT_DATE(),'BUILD JENUA','guactimusprime');
INSERT INTO TODO (DONE,ID,PRIORITY,TARGET_DATE,DESCRIPTION,USERNAME)
VALUES (false,7,1 ,CURRENT_DATE(),'FIGURE OUT THE GOOGLE PLAY ISSUE','guactimusprime');
INSERT INTO TODO (DONE,ID,PRIORITY,TARGET_DATE,DESCRIPTION,USERNAME)
VALUES (false,8,0 ,CURRENT_DATE(),'DO THE GENSHIN REPUTATION','guactimusprime');